// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package authv1
import (
 context "context"
 grpc "google.golang.org/grpc"
 codes "google.golang.org/grpc/codes"
 status "google.golang.org/grpc/status"
)
const _=grpc.SupportPackageIsVersion8
type AuthServiceClient interface{ValidateToken(context.Context,*ValidateTokenRequest,...grpc.CallOption)(*ValidateTokenResponse,error);GetUser(context.Context,*GetUserRequest,...grpc.CallOption)(*GetUserResponse,error);CheckPermission(context.Context,*CheckPermissionRequest,...grpc.CallOption)(*CheckPermissionResponse,error)}
type authServiceClient struct{cc grpc.ClientConnInterface}
func NewAuthServiceClient(cc grpc.ClientConnInterface)AuthServiceClient{return &authServiceClient{cc}}
func(c *authServiceClient)ValidateToken(ctx context.Context,in *ValidateTokenRequest,opts ...grpc.CallOption)(*ValidateTokenResponse,error){out:=new(ValidateTokenResponse);err:=c.cc.Invoke(ctx,"/auth.v1.AuthService/ValidateToken",in,out,opts...);if err!=nil{return nil,err};return out,nil}
func(c *authServiceClient)GetUser(ctx context.Context,in *GetUserRequest,opts ...grpc.CallOption)(*GetUserResponse,error){out:=new(GetUserResponse);err:=c.cc.Invoke(ctx,"/auth.v1.AuthService/GetUser",in,out,opts...);if err!=nil{return nil,err};return out,nil}
func(c *authServiceClient)CheckPermission(ctx context.Context,in *CheckPermissionRequest,opts ...grpc.CallOption)(*CheckPermissionResponse,error){out:=new(CheckPermissionResponse);err:=c.cc.Invoke(ctx,"/auth.v1.AuthService/CheckPermission",in,out,opts...);if err!=nil{return nil,err};return out,nil}
type AuthServiceServer interface{ValidateToken(context.Context,*ValidateTokenRequest)(*ValidateTokenResponse,error);GetUser(context.Context,*GetUserRequest)(*GetUserResponse,error);CheckPermission(context.Context,*CheckPermissionRequest)(*CheckPermissionResponse,error);mustEmbedUnimplementedAuthServiceServer()}
type UnimplementedAuthServiceServer struct{}
func(UnimplementedAuthServiceServer)ValidateToken(context.Context,*ValidateTokenRequest)(*ValidateTokenResponse,error){return nil,status.Errorf(codes.Unimplemented,"method ValidateToken not implemented")}
func(UnimplementedAuthServiceServer)GetUser(context.Context,*GetUserRequest)(*GetUserResponse,error){return nil,status.Errorf(codes.Unimplemented,"method GetUser not implemented")}
func(UnimplementedAuthServiceServer)CheckPermission(context.Context,*CheckPermissionRequest)(*CheckPermissionResponse,error){return nil,status.Errorf(codes.Unimplemented,"method CheckPermission not implemented")}
func(UnimplementedAuthServiceServer)mustEmbedUnimplementedAuthServiceServer(){}
func RegisterAuthServiceServer(s grpc.ServiceRegistrar,srv AuthServiceServer){s.RegisterService(&AuthService_ServiceDesc,srv)}
func _AuthService_ValidateToken_Handler(srv interface{},ctx context.Context,dec func(interface{})error,interceptor grpc.UnaryServerInterceptor)(interface{},error){in:=new(ValidateTokenRequest);if err:=dec(in);err!=nil{return nil,err};if interceptor==nil{return srv.(AuthServiceServer).ValidateToken(ctx,in)};info:=&grpc.UnaryServerInfo{Server:srv,FullMethod:"/auth.v1.AuthService/ValidateToken"};handler:=func(ctx context.Context,req interface{})(interface{},error){return srv.(AuthServiceServer).ValidateToken(ctx,req.(*ValidateTokenRequest))};return interceptor(ctx,in,info,handler)}
func _AuthService_GetUser_Handler(srv interface{},ctx context.Context,dec func(interface{})error,interceptor grpc.UnaryServerInterceptor)(interface{},error){in:=new(GetUserRequest);if err:=dec(in);err!=nil{return nil,err};if interceptor==nil{return srv.(AuthServiceServer).GetUser(ctx,in)};info:=&grpc.UnaryServerInfo{Server:srv,FullMethod:"/auth.v1.AuthService/GetUser"};handler:=func(ctx context.Context,req interface{})(interface{},error){return srv.(AuthServiceServer).GetUser(ctx,req.(*GetUserRequest))};return interceptor(ctx,in,info,handler)}
func _AuthService_CheckPermission_Handler(srv interface{},ctx context.Context,dec func(interface{})error,interceptor grpc.UnaryServerInterceptor)(interface{},error){in:=new(CheckPermissionRequest);if err:=dec(in);err!=nil{return nil,err};if interceptor==nil{return srv.(AuthServiceServer).CheckPermission(ctx,in)};info:=&grpc.UnaryServerInfo{Server:srv,FullMethod:"/auth.v1.AuthService/CheckPermission"};handler:=func(ctx context.Context,req interface{})(interface{},error){return srv.(AuthServiceServer).CheckPermission(ctx,req.(*CheckPermissionRequest))};return interceptor(ctx,in,info,handler)}
var AuthService_ServiceDesc=grpc.ServiceDesc{ServiceName:"auth.v1.AuthService",HandlerType:(*AuthServiceServer)(nil),Methods:[]grpc.MethodDesc{{MethodName:"ValidateToken",Handler:_AuthService_ValidateToken_Handler},{MethodName:"GetUser",Handler:_AuthService_GetUser_Handler},{MethodName:"CheckPermission",Handler:_AuthService_CheckPermission_Handler}},Streams:[]grpc.StreamDesc{},Metadata:"proto/auth/v1/auth.proto"}
